create table public.registros_financeiros (
  id bigint generated by default as identity not null,
  nome text not null,
  tipo text not null,
  categoria text not null,
  quantidade numeric not null default 1,
  valor_unitario numeric not null,
  valor_total numeric not null,
  data_cadastro timestamp with time zone null default now(),
  constraint registros_financeiros_pkey primary key (id),
  constraint registros_financeiros_tipo_check check (
    (
      tipo = any (array['entrada'::text, 'saida'::text])
    )
  )
) TABLESPACE pg_default;